### ISSUE TITLE
dyndle CLI does not support updating/removing environments

### ISSUE THREAD

**Issue by pjbeemster** [dyndle/dyndle-tools#1]
Dyndle CLI tool has verbs for `add-environment` and `list-environments`, but once an environment is added, it cannot be updated or removed using the tool. Need to either hand-edit the environments.json file and/or delete the environments file altogether to start over.

**Comment by quirijnslings** [comment]
We will pick this up shortly

**Comment by quirijnslings** [comment]
Fixed in https://github.com/dyndle/dyndle-tools/tree/v1.0.1.
You can download the latest CLI from https://www.dyndle.com/download.html.
