### ISSUE TITLE
dyndle CLI throws error when installing over HTTPS

### ISSUE THREAD

**Issue by pjbeemster** [dyndle/dyndle-tools#2]
When trying to install the Dyndle Content Manager Items, dyndle CLI fails with a WCF binding error on TLS/SSL enabled Tridion Content Manager host: "Error: Contract requires Session, but Binding 'BasicHttpBinding' doesn't support it or isn't configured properly to support it." 

Steps to reproduce:

`.\dyndle.exe add-environment --name devlab --username *** --password *** --url https://sdlcm-author.company.com --default`
> Successfully added environment

`.\dyndle.exe list-environments`
> [devlab]* https://sdlcm-author.company.com

`.\dyndle.exe install --environment devlab --dyndle-folder tcm:12-1010-2 --dyndle-sg tcm:12-1008-4`
> Error: Contract requires Session, but Binding 'BasicHttpBinding' doesn't support it or isn't configured properly to support it.

**Comment by quirijnslings** [comment]
I can confirm this is a bug, will push the fix asap

**Comment by quirijnslings** [comment]
Fixed in https://github.com/dyndle/dyndle-tools/tree/v1.0.1.
You can download the latest CLI from https://www.dyndle.com/download.html.
