### ISSUE TITLE
dyndle.exe install fails with "Name must be unique" exception

### ISSUE THREAD

**Issue by pjbeemster** [dyndle/dyndle-tools#3]
Hopefully user error, but running into an issue when trying to install Dyndle on CM-side:

```
C:\Temp>dyndle --version
Dyndle.Tools.CLI 1.0.1.0

C:\Temp>dyndle.exe install --environment devlab --dyndle-folder tcm:12-1010-2 --dyndle-sg tcm:12-1008-4
Error: Name must be unique for items of type: Schema within this Folder and its BluePrint context. Source or sources of conflict: tcm:12-1031-8.
```
Conflict item `tcm:12-1031-8` is the `Preview page` Parameters Schema.

The `--dyndle-folder` is an empty local folder in a new child publication dedicated to Dyndle. The publication inherits the DD4T TBBs from its parent, and does not have child publications (yet).

Folder paths:
- DD4T (inherited): Building Blocks > Modules > DD4T > Developer
- Dyndle (local): Building Blocks > Modules > Dyndle > Developer

<img width="1287" alt="dyndle-blueprint" src="https://user-images.githubusercontent.com/8088992/84935845-2d4bac00-b08e-11ea-88a1-f77c12c68daf.png">

Also, while above `install` command successfully connects, repeated runs intermittently fail with a "Provided URI scheme invalid" exception:
```
C:\Temp>dyndle.exe install --environment devlab --dyndle-folder tcm:12-1011-2 --dyndle-sg tcm:12-1008-4
Error: The provided URI scheme 'https' is invalid; expected 'http'.
Parameter name: via
```

Thanks,
Peter

**Comment by pjbeemster** [comment]
With some log statements added:
 
`Preview parameters` is the first `importItem` in `itemsWithoutDependencies` in the first iteration (stopper == 10)
https://github.com/dyndle/dyndle-tools/blob/af9013d500bc82e4a30615415e10a7539e1923cd/src/Dyndle.Tools.Installer/Installer.cs#L77

The `provided URI scheme 'https'` exception is thrown by the UploadClient in `Installer.ImportTBB()`. Will double check server config.

**Comment by quirijnslings** [comment]
We fixed the issue (and a bit more). Thanks for the pull request, PJ!
See https://github.com/dyndle/dyndle-tools/tree/v1.0.2 and/or download the latest from https://www.dyndle.com/download.html.
